# このファイルはSpring Bootアプリの起動時の設定を記述するファイル

# アプリの名前 ログや監視ツールが使うらしい
spring.application.name=qiita-summary-notifier

# PostgreSQLのドライバ
spring.datasource.driver-class-name=org.postgresql.Driver

# ログの出力レベルをDEBUGにする
logging.level.com.portfolio.qiita_summary_notifier=DEBUG

# アプリ起動時にDBが初期化される
# よくわかってない
spring.sql.init.mode=always

# コンソール出力時の文字コードをUTF-8に指定
logging.charset.console=UTF-8

# application-local.propertiesを読み込む
spring.profiles.include=local

# DBとJavaの名前問題を自動で解決してくれるオプション
# created_at(DB)とcreatedAt(Java)を自動で変換してくれるやつらしい
mybatis.configuration.map-underscore-to-camel-case=true